### PR TITLE
Various Games 

### PR DESCRIPTION
**Pull request by oshaboy**
This Pull Request Adds support for

Donkey Kong (Gameboy)
Donkey Kong Jr. (NES)
Donkey Kong 3 (NES)
Mario Bros. (NES)
Kid Icarus (NES)
Wrecking Crew (NES)
Balloon Fight (NES)
Pitfall! (2600)
Pitfall II - Lost Caverns (2600)
Gumshoe (NES) (Preconfigure Zapper if you include this)
Alex Kidd in Miracle World (SMS) 
Alex Kidd in the Enchanted Castle (MD)
Flicky (MD)

### CODE REVIEW

**Comment by oshaboy** [comment]
To clarify, Pitfall! should work if Atari 2600 support is added.

**Comment by alistairaitcheson** [comment]
Heya! Sorry I didn't notice this earlier but thank you so much for adding these games in! I'll give it a test and merge it in as soon as possible :)

**Comment by oshaboy** [comment]
Take your time

**Review by alistairaitcheson — APPROVED** [review]

**Comment by alistairaitcheson** [comment]
Sorry for taking so long on this! Thank you so much for contributing so many games :)

**Pull request merged**
